name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/meu_app:${{ github.sha }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/meu_app:${{ github.sha }}

      - name: SSH and deploy on server
        uses: appleboy/ssh-action@master
        with:
          host: 201.23.3.86
          username: aluno
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/meu_app:${{ github.sha }}
            docker stop meu_app || true
            docker rm meu_app || true
            docker run -d -p ${{ secrets.SSH_PORT }}:8088 --name meu_app ${{ secrets.DOCKER_USERNAME }}/meu_app:${{ github.sha }}
